/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.alissonlima;

import com.google.gson.Gson;
import software.amazon.awssdk.services.sns.model.SnsException;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.services.sqs.model.DeleteMessageRequest;
import software.amazon.awssdk.services.sqs.model.GetQueueUrlRequest;
import software.amazon.awssdk.services.sqs.model.Message;
import software.amazon.awssdk.services.sqs.model.ReceiveMessageRequest;

import java.util.List;

/**
 * Recebe uma mensagem de uma fila do SQS
 */
public class Receiver {

    public static void main(String[] args) {
        try {
            SqsClient sqsClient = SqsClient.create();

            GetQueueUrlRequest getQueueUrlRequest = GetQueueUrlRequest.builder().queueName("Calc-Sum").build();
            String queueUrl = sqsClient.getQueueUrl(getQueueUrlRequest).queueUrl();

            while (true) {
                System.out.println("Consultado mensagens");
                ReceiveMessageRequest receiveMessageRequest = ReceiveMessageRequest.builder()
                        .queueUrl(queueUrl)
                        .maxNumberOfMessages(5)
                        .waitTimeSeconds(10)
                        .build();
                List<Message> messages = sqsClient
                        .receiveMessage(receiveMessageRequest)
                        .messages();
                if (messages.isEmpty()) continue;

                for (Message message : messages) {
                    SQSMessage sqsMessage = new Gson().fromJson(message.body(), SQSMessage.class);
                    System.out.println(sqsMessage.getMessage());

                    // A mensagem deve ser programaticamente excluída pois ela não é
                    // removida automaticamente da fila
                    DeleteMessageRequest deleteMessageRequest = DeleteMessageRequest.builder()
                            .queueUrl(queueUrl)
                            .receiptHandle(message.receiptHandle())
                            .build();
                    sqsClient.deleteMessage(deleteMessageRequest);
                }
            }

        } catch (SnsException e) {
            System.err.println(e.awsErrorDetails().errorMessage());
            System.exit(1);
        }
    }
}
